# This workflow will build APOD app and run playwright tests against same.
name: run-daily-tests

on:
  push: 
    branches: [ "master"]
  pull_request:
    branches: 
      - master
    types: [closed]
  workflow_dispatch:

jobs:
  run-daily-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@master
      - name: Pull docker image for apodview and apodapi 
        shell: sh
        run: |
          #!/bin/sh
          # Pull apod-view:latest 
          sudo docker pull mail2prajwal12/apod-view:latest
          sudo docker run -d -p 7777:7777 --name apod-view mail2prajwal12/apod-view:latest
          # Pull the Docker Image 
          sudo docker pull mail2prajwal12/apod-api:latest
          sudo docker run -d -p 8888:8888 --name apod-api mail2prajwal12/apod-api:latest
      - name: run the playwright tests
        run: npm ci && ENV=stable HEADLESS=false npx cucumber-js --tags=@all