# This workflow will build APOD app and run playwright tests against same.
name: run-daily-tests

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  run-daily-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@master
      - name: Pull docker image for apodview and apodapi 
        shell: sh
        run: |
          #!/bin/sh
          # Pull apod-view:latest 
          sudo docker pull mail2prajwal12/apod-view:latest
          sudo docker run -itd -p 7777:7777 --name apod-view mail2prajwal12/apod-view:latest
          # Pull the Docker Image 
          sudo docker pull mail2prajwal12/apod-api:latest
          sudo docker run -itd -p 8888:8888 --name apod-api mail2prajwal12/apod-api:latest
      - name: Run the playwright tests
        run: npm ci && ENV=stable npx cucumber-js --tags=@all
      - name: Archive test results
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: reports